param(
    [string]$OutputPath = (Join-Path $PSScriptRoot "MobData.lua")
)

$ErrorActionPreference = "Stop"

$locales = [ordered]@{
    enUS = ""
    deDE = "de/"
    frFR = "fr/"
}

$classifications = 1, 2, 3, 4
$classificationNames = @{
    "1" = "Elite"
    "2" = "Rare Elite"
    "3" = "World Boss"
    "4" = "Rare"
}

function Get-ListviewData {
    param([string]$Url)

    $response = Invoke-WebRequest -UseBasicParsing $Url
    $response.RawContentStream.Position = 0
    $reader = [System.IO.StreamReader]::new(
        $response.RawContentStream,
        [System.Text.UTF8Encoding]::new($false),
        $true
    )
    $html = $reader.ReadToEnd()
    $reader.Dispose()

    if ($html -match '"_truncated":1') {
        throw "Wowhead truncated the NPC list at $Url; split this filter into smaller ranges"
    }

    $match = [regex]::Match(
        $html,
        '"template":"npc","data":(\[.*?\])(?:,"extraCols"|}\);</script>)',
        [System.Text.RegularExpressions.RegexOptions]::Singleline
    )

    if (-not $match.Success) {
        if ($html -notmatch '"template":"npc"') {
            return @()
        }

        throw "Could not find NPC list data at $Url"
    }

    return @($match.Groups[1].Value | ConvertFrom-Json)
}

function ConvertTo-LuaString {
    param([string]$Value)

    $escaped = $Value.Replace('\', '\\').Replace('"', '\"')
    $escaped = $escaped.Replace("`r", '\r').Replace("`n", '\n')
    return '"' + $escaped + '"'
}

$mobData = [ordered]@{}
foreach ($locale in $locales.Keys) {
    $byName = @{}

    foreach ($classification in $classifications) {
        $urls = @()

        if ($classification -eq 1) {
            foreach ($minimumLevel in 1, 11, 21, 31, 41, 51, 61, 71) {
                $maximumLevel = $minimumLevel + 9
                $urls += "https://www.wowhead.com/classic/$($locales[$locale])npcs/min-level:$minimumLevel/max-level:$maximumLevel/classification:$classification"
            }
        } elseif ($classification -eq 3) {
            # World bosses use a skull level and disappear when numeric level filters are applied.
            $urls += "https://www.wowhead.com/classic/$($locales[$locale])npcs/classification:$classification"
        } else {
            $urls += "https://www.wowhead.com/classic/$($locales[$locale])npcs/min-level:1/max-level:80/classification:$classification"
        }

        foreach ($url in $urls) {
            foreach ($npc in (Get-ListviewData $url)) {
                if ([int]$npc.classification -ne $classification) {
                    throw "Unexpected classification for NPC $($npc.id) from $url"
                }

                $name = [string]$npc.name

                if ([string]::IsNullOrWhiteSpace($name)) {
                    continue
                }

                $existing = $byName[$name]

                if ($null -eq $existing -or $classification -eq 3 -or
                    ($classification -eq 2 -and $existing -ne 3) -or
                    ($classification -eq 1 -and $existing -eq 4)) {
                    $byName[$name] = $classification
                }
            }
        }
    }

    $mobData[$locale] = $byName
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("-- Generated by GenerateMobData.ps1 from Wowhead Classic NPC list data.")
$lines.Add("-- Source filters: levels 1-80; Elite, Rare Elite, World Boss, and Rare.")
$lines.Add("-- World Boss has no numeric level filter because skull-level NPCs are otherwise excluded.")
$lines.Add("-- Do not edit this file manually.")
$lines.Add("")
$lines.Add("local mobClassifications = {")

foreach ($locale in $mobData.Keys) {
    $lines.Add("    $locale = {")

    foreach ($name in @($mobData[$locale].Keys | Sort-Object)) {
        $lines.Add("        [$(ConvertTo-LuaString $name)] = $($mobData[$locale][$name]),")
    }

    $lines.Add("    },")
}

$lines.Add("}")
$lines.Add("")
$lines.Add("local classificationNames = {")

foreach ($classification in $classifications) {
    $lines.Add("    [$classification] = $(ConvertTo-LuaString $classificationNames[[string]$classification]),")
}

$lines.Add("}")
$lines.Add("")
$lines.Add("local localeAliases = {")
$lines.Add('    enGB = "enUS",')
$lines.Add("}")
$lines.Add("")
$lines.Add("function getMobClassification(name, locale)")
$lines.Add("    locale = locale or GetLocale()")
$lines.Add("    locale = localeAliases[locale] or locale")
$lines.Add("    local localizedData = mobClassifications[locale] or mobClassifications.enUS")
$lines.Add("    local classification = localizedData[name]")
$lines.Add("")
$lines.Add("    return classificationNames[classification]")
$lines.Add("end")
$lines.Add("")

[System.IO.File]::WriteAllLines($OutputPath, $lines, [System.Text.UTF8Encoding]::new($false))

foreach ($locale in $mobData.Keys) {
    Write-Output "${locale}: $($mobData[$locale].Count) classified NPC names"
}
